years:
  name: years
  label: Year
  label_plural: Years
  kind: numeric
  template: years
  data:
    min: 1880
    max: 2019

years2:
  name: years
  label: Years
  label_plural: Years
  kind: numeric
  template: range
  data:
    min: 1880
    max: 2019

genres:
  name: genres
  label: Genre
  label_plural: Genres
  kind: string
  template: enum

actors:
  name: actors
  label: Actor
  label_plural: Actors
  kind: multi_string
  template: none
