defaults: &defaults
  path_prefix: 'templates'
  template_extensions:
    - 'slimstache'
  template_namespace: 'JST'

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
