development: &development
  facebook:
    id: "833040550095705"
    secret: "10c86d2f8811fed0e2120352a8146e17"
  twitter:
    id: "kxa2M6tVJNKsP74H31dlPqUNe"
    secret: "lDlvfUmnSbRJqdKO8AHv1pUbUortjcAzLgG9ZQRInHKZvuu5JJ"
  google_oauth2:
    id: "29511162814-k3dnk117e23qgp0giiokom4tov5ftifo.apps.googleusercontent.com"
    secret: "iP9h9C79g8VlAcG3vMU1nwT4"
    name: "google"

staging:
  facebook:
    id: "1529910983936462"
    secret: "235f765b931ed1268497eb89654332fc"
  twitter:
    id: "kxa2M6tVJNKsP74H31dlPqUNe"
    secret: "lDlvfUmnSbRJqdKO8AHv1pUbUortjcAzLgG9ZQRInHKZvuu5JJ"
  google_oauth2:
    id: "29511162814-pg73rr3d9mt54t5dccrbb17rjv63i1k8.apps.googleusercontent.com"
    secret: "1TAAokPw3nRfefs2HE-nACbw"
    name: "google"

production:
  facebook:
    id: "1576246925945571"
    secret: "e1e151a74fca65cc68d4b71c9e1d3e80"
  twitter:
    id: "lYBYOWLPFONzKanWGh5NIME9u"
    secret: "V0mlQPfxhk1gcDPskrmOcxvA0H6Oi8UpGZ7vyvMiC5AbAtnriY"
  google_oauth2:
    id: "757427059785-raltb4i5he5lkjij7f84vno923f6gdi6.apps.googleusercontent.com"
    secret: "ke4dKP9PZJBPSuYgcWBkqOxc"
    name: "google"

test:
  <<: *development
