# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40dea03b6f30fbe04b8c782f9e2b86aa3ab4003ce6ee4eb603f174685ef6b159b55051305c928bfc8a810ece7b2345aa7f253c70b6583fd5c2bd07899ea5bfee

test:
  secret_key_base: 2a30723905dd1a05a501f16dc21a56b2fb7d6799e2f0a7380116a3cdb2e78c325b8c899986293a7f5166817a6c1a888ac4f9da5d151bc11832c1be6b982d75ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
