reviews:
  alternatives:
    - black
    - crimson

actors:
  alternatives:
    - displayed
    - hidden
  metadata:
    displayed:
      visible: true
    hidden:
      visible: false

weekend:
  alternatives:
    - weekend
    - weekday
  algorithm: "Split::Algorithms::Weekend"
