reviews:
  alternatives:
    - black
    - crimson
actors:
  alternatives:
    - displayed
    - hidden
  metadata:
    displayed:
      visible: true
    hidden:
      visible: false
new_year:
  alternatives:
    - 'HAPPY NY'
    - 'TopRater'
  algorithm: "Split::Algorithms::Weekend"
